kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: demo-app-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-app-web
  minReplicas: 2
  maxReplicas: 12
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 75
